owner: hollowsoftware
repo: status
sites:
  - name: METACHESS
    url: https://metachess.org
status-website:
  cname: status.metachess.org
  name: METACHESS Status
  introTitle: "METACHESS System Status"
  introMessage: "Live status and uptime monitoring for METACHESS."
  navbar:
    - title: Main site
      href: https://metachess.org
